apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-pipelines-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openshift-pipelines-operator
  template:
    metadata:
      labels:
        name: openshift-pipelines-operator
    spec:
      serviceAccountName: openshift-pipelines-operator
      containers:
        - name: openshift-pipelines-operator
          # Replace this with the built image name
          #image: quay.io/openshift-pipeline/openshift-pipelines-operator:v0.3.1-1
          image: akihikokuroda/openshift-pipelines-operator:v17
          command:
          - openshift-pipelines-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "openshift-pipelines-operator"
          volumeMounts:
          - name: webhooks
            mountPath: /deploy/resources/webhooks/webhooks.yaml
            subPath: webhooks.yaml
          - name: webhooks-sink
            mountPath: /deploy/resources/webhooks-sink/webhooks-sink.yaml
            subPath: webhooks-sink.yaml
      volumes:
      - name: webhooks
        configMap:
          name: webhooks
          items:
          - key: webhooks.yaml
            path: webhooks.yaml
            mode: 0777
      - name: webhooks-sink
        configMap:
          name: webhooks-sink
          items:
          - key: webhooks-sink.yaml
            path: webhooks-sink.yaml
            mode: 0777
