apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-pipelines-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openshift-pipelines-operator
  template:
    metadata:
      labels:
        name: openshift-pipelines-operator
    spec:
      serviceAccountName: openshift-pipelines-operator
      containers:
        - name: openshift-pipelines-operator
          # Replace this with the built image name
          #image: quay.io/openshift-pipeline/openshift-pipelines-operator:v0.3.1-1
          image: akihikokuroda/openshift-pipelines-operator:v17
          command:
          - openshift-pipelines-operator
          imagePullPolicy: Always
          volumeMounts:
          - name: webhook
            mountPath: /deploy/resources/aaa/webhook.yaml
            subPath: webhook.yaml
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "openshift-pipelines-operator"
      volumes:
      - name: webhook
        configMap:
          name: tekton-pipelines-webhook
          items:
          - key: webhook.yaml
            path: webhook.yaml
            mode: 0777