apiVersion: v1
kind: ConfigMap
metadata:
  name: webhooks-sink
  namespace: openshift-pipelines-operator
data:
  webhooks-sink.yaml: |
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    metadata:
      name: webhooks-extension-sink
      namespace: tekton-pipelines
      labels:
        app: webhooks-extension-sink
    spec:
      runLatest:
        configuration:
          revisionTemplate:
            spec:
              container:
                image: "github.com/tektoncd/experimental/webhooks-extension/cmd/sink"
                imagePullPolicy: Always
                ports:
                - containerPort: 8080
                livenessProbe:
                  httpGet:
                    path: /liveness
                readinessProbe:
                  httpGet:
                    path: /readiness
                env:
                - name: PORTs
                #- name: PORT
                  value: "8080"
                #- name: INSTALLED_NAMESPACE
                #  valueFrom:
                #    fieldRef:
                #      fieldPath: metadata.namespace
              serviceAccountName: tekton-pipelines-controller
