---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: webhooks-extension-sink
  namespace: tekton-pipelines
  labels:
    app: webhooks-extension-sink
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: "akihikokuroda/sink:v1"
            imagePullPolicy: Always
            ports:
            - containerPort: 8080
            livenessProbe:
              httpGet:
                path: /liveness
            readinessProbe:
              httpGet:
                path: /readiness
            env:
            - name: PORT
              value: "8080"
            - name: INSTALLED_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      serviceAccountName: tekton-pipelines-controller
---
apiVersion: v1
kind: Service
metadata:
  name: webhooks-extension
  namespace: tekton-pipelines
  labels:
    app: webhooks-extension
    tekton-dashboard-extension: "true"
  annotations:
    tekton-dashboard-display-name: webhooks-extension
    tekton-dashboard-endpoints: "webhooks"
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: webhooks-extension
